"""Added Explnation Session Columns -> Explnantions Table -> Explanations MetadataTable

Revision ID: c09c7233579e
Revises: e12c77d8240c
Create Date: 2026-07-04 12:54:49.107714

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c09c7233579e"
down_revision: Union[str, Sequence[str], None] = "e12c77d8240c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("concept_mastery")
    op.drop_index(
        op.f("idx_chunk_embedding"),
        table_name="chunk_embeddings",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.drop_table("chunk_embeddings")
    op.drop_index(op.f("idx_concept_domain"), table_name="concepts")
    op.drop_index(op.f("idx_concept_name"), table_name="concepts")
    op.drop_table("concepts")
    op.drop_table("feedback")
    op.drop_index(op.f("idx_mastery_concept"), table_name="concept_mastery")
    op.drop_index(op.f("idx_mastery_user"), table_name="concept_mastery")
    op.drop_table("concept_mastery")
    op.drop_table("explanation_sessions")
    op.drop_table("knowledge_sources")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("idx_question_embedding"),
        table_name="question_embeddings",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.drop_table("question_embeddings")
    op.drop_table("document_chunks")
    op.drop_table("explaination_embeddings")
    op.drop_table("explanations")
    op.drop_table("evaluations")
    op.drop_table("learner_profiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learner_profiles",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "academic_level",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "institution",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "major", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "learning_style",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "preferred_explanation_style",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "preferred_difficulty",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "domain",
            postgresql.ARRAY(sa.VARCHAR(length=30)),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("learner_profiles_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("learner_profiles_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("learner_profiles_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "evaluations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "explanation_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "metric_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["explanation_id"],
            ["explanations.id"],
            name=op.f("evaluations_explanation_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("evaluations_pkey")),
    )
    op.create_table(
        "explanations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "session_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "model_name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "generated_explanation",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "difficulty_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "explanation_style",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "token_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["explanation_sessions.id"],
            name=op.f("explanations_session_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("explanations_pkey")),
    )
    op.create_table(
        "explaination_embeddings",
        sa.Column("session_id", sa.UUID(), sa.UUID(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["explanations.id"],
            name=op.f("explaination_embeddings_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "session_id", name=op.f("explaination_embeddings_pkey")
        ),
    )
    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("chunk_text", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge_sources.id"],
            name=op.f("document_chunks_source_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_chunks_pkey")),
    )
    op.create_table(
        "question_embeddings",
        sa.Column(
            "session_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["explanation_sessions.id"],
            name=op.f("question_embeddings_session_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "session_id", name=op.f("question_embeddings_pkey")
        ),
    )
    op.create_index(
        op.f("idx_question_embedding"),
        "question_embeddings",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "knowledge_sources",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "source_name", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "source_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "uploaded_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("knowledge_sources_pkey")),
    )
    op.create_table(
        "explanation_sessions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "topic",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("explanation_sessions_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("explanation_sessions_pkey")),
    )
    op.create_table(
        "feedback",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "explanation_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column("rating", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "clarity_score", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "usefulness_score",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "correctness_score",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("comments", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["explanation_id"],
            ["explanations.id"],
            name=op.f("feedback_explanation_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_pkey")),
    )
    op.create_table(
        "concepts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "name", sa.VARCHAR(length=150), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "difficulty",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "domain", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "isactive", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("concepts_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("concepts_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_concept_name"), "concepts", ["name"], unique=False
    )
    op.create_index(
        op.f("idx_concept_domain"), "concepts", ["domain"], unique=False
    )

    op.create_table(
        "concept_mastery",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "concept_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "mastery_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_interaction",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("concept_mastery_concept_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("concept_mastery_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("concept_mastery_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "concept_id",
            name=op.f("uq_user_concept_mastery"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_mastery_user"), "concept_mastery", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_mastery_concept"),
        "concept_mastery",
        ["concept_id"],
        unique=False,
    )

    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("chunk_embeddings_chunk_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", name=op.f("chunk_embeddings_pkey")
        ),
    )
    op.create_index(
        op.f("idx_chunk_embedding"),
        "chunk_embeddings",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    # ### end Alembic commands ###
