"""Initial baseline with explanation sessions

Revision ID: f5df1fb94d19
Revises:
Create Date: 2026-07-04 14:03:25.228651

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f5df1fb94d19"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
