FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /api

RUN apt-get update && apt-get -y install libpq-dev gcc

COPY pyproject.toml poetry.lock /api/

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --without dev

COPY . /api/

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
